knp_paginator:
  page_range: 6 # nombre éléments affichés par page
  default_options:
    page_name: page # nom du parametre de page
    sort_field_name: sort # nom du parametre de tri
    sort_direction_name : direction # nom du parametre de sens de tri
    distinct: true # s'assure de la distinction des éléments retournés par l'orm
    filter_field_name: filter_field # nom du param stockant le champ à filtrer
    filter_value_name: filter_value # nom param stockant la valeur du filtre
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/sortable.html.twig'
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'
