vich_uploader:
    db_driver: orm

    mappings:
       bien_image:
           uri_prefix: '%bien_image%'
           upload_destination: '%kernel.project_dir%/public%bien_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
