name: camping
recipe: symfony
config:
  webroot: public
services:
  myservice:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom: 
      - appserver
  appserver:
    type: php
  database:
    portforward: 3307
  node:
    type: node:14
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node
