name: camping
recipe: symfony
config:
  webroot: public
services:
  database:
    portforward: 3307
  node:
    type: node:14
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node
